version: '2'

services:
  serviceDb:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sicuro
